#!/bin/sh

set -o noclobber
set -o errexit
set -o nounset

[ "$#" -lt 2 ] && { echo >&2 'usage: ejf <file1.java> <file2.java> ...'; exit 3; }

dir="$(cd "$(dirname "$0")"; pwd -P)"

styleUrl="https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml"
styleFile="$(echo "$styleUrl" | sed -re 's/^.*\/([^\/]+)$/\1/')"
curl -f -L -# -o "$styleFile" "$styleUrl" || { rm "$file"; exit 1; }

src="$dir/src/ejf/Main.java"
bin="$dir/bin/ejf-jar-with-dependencies.jar"
cls="$dir/bin/ejf/Main.class"
if [ "$src" -nt "$cls" ] ; then
  echo "Recompiling $src ..."
  javac -d "$bin" "$src"
  touch -r "$src" "$cls"
fi

java -cp "$bin" ejf.Main "$styleFile" "$@"
